apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ template "trino.coordinator" . }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: {{ .Values.server.config.path }}
            name: config-volume
          - mountPath: {{ .Values.server.config.path }}/catalog
            name: catalog-volume
        ports:
          - name: http1
            containerPort: {{ .Values.server.config.http.port }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /v1/info
        readinessProbe:
          httpGet:
            path: /v1/info/ready
        #  exec:
        #    command:
        #      - /bin/sh
        #      - /etc/trino/probe-exec.sh
          initialDelaySeconds: 20
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "trino.coordinator" . }}
        - name: catalog-volume
          secret:
            secretName: trino-connectors