apiVersion: v1
kind: Service
metadata:
  name: {{ template "trino.coordinator" . }}-headless-service
spec:

  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    service.istio.io/canonical-name: {{ template "trino.coordinator" . }}
  ports:
    - name: http 
      protocol: TCP
      port: 8080
      targetPort: 8080
  sessionAffinity: None

