apiVersion: v1
appVersion: "356"
description: High performance, distributed SQL query engine for big data
name: trino
version: 0.0.1
home: https://trino.io
icon: https://trino.io/assets/images/trino-logo/trino-ko_tiny-alt.svg
sources:
  - https://github.com/trinodb/trino
keywords:
  - trino
  - trinosql
  - trinodb
  - presto
  - prestosql
  - prestodb
  - "big data"
  - database
  - sql
  - "query engine"
  - "high performance"
